### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Embiggenerd** [microsoft/TypeScript-React-Conversion-Guide#17]
Error when running npx build after configuring ts, editing build pipeline:

ERROR in ./src/app.jsx
Module build failed: Error: It looks like you're using an old webpack version without hooks support. If you're using awesome-script-loader with React storybooks consider upgrading @storybook/react to at least version 4.0.0-alpha.3
    at Object.ensureInstance (/home/code123/Documents/js/TypeScript-React-Conversion-Guide/TicTacToe_JS/node_modules/awesome-typescript-loader/src/instance.ts:142:9)
    at compiler (/home/code123/Documents/js/TypeScript-React-Conversion-Guide/TicTacToe_JS/node_modules/awesome-typescript-loader/src/index.ts:45:19)
    at Object.loader (/home/code123/Documents/js/TypeScript-React-Conversion-Guide/TicTacToe_JS/node_modules/awesome-typescript-loader/src/index.ts:14:12)

**Comment by jingbogit** [comment]
Thanks.

btw, I got this error after following the fix:

> ERROR in [at-loader] ./node_modules/@types/react/index.d.ts:377:23 
>     TS2583: Cannot find name 'Set'. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.

My solution was to follow the suggestion and changing `lib` to "es2015".

**Comment by orta** [comment]
All libs are updated now, so this shouldn't happen.
